### ISSUE TITLE
error internal fs/utils

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/vocabulary-recommender#11]
Hi, I installed the npm package (for output see #10) and then used the command ``. I expected recommendations "person", but got an error on fs/utils instead. My output:

```
user@machine vocabulary-recommender % vocabulary-recommender -t person -c class
internal/fs/utils.js:314
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir '~/Vocabulary_recommender'
    at Object.mkdirSync (fs.js:1009:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/vocabulary-recommender/dist/recommend.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '~/Vocabulary_recommender'
}
```

**Comment by philipperenzen** [comment]
This issue seems to be related to a previous version of the npm vocabulary-recommender package (v1.0.3). We recommend to update the package or remove the installed 'vocabulary-recommender' package in the 'node_modules' folder and install it again.

**Comment by rlzijdeman** [comment]
Hi, I did another run trying to install via NPM, but instructions provided on the GitHub page are simply not good enough. I have used this website https://radixweb.com/blog/installing-npm-and-nodejs-on-windows-and-mac to install npm. But installation of the vocabulary-recommender results in various errors. I advice to remove this as an option or to enhance documentation.

**Comment by philipperenzen** [comment]
^ This issue was resolved internally and will be closed.

Please make a new issue when facing installation problems or for suggestions and improvements regarding documentation.
