### ISSUE TITLE
is link to yarn installation correct

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/vocabulary-recommender#8]
Hi, in the readme, I am referred to this link https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable , but on that web page I get a warning, that this installation only is for 'older' version (<2.0). Is that reference correct?

**Comment by philipperenzen** [comment]
Thanks for the feedback! It seems the old link was referring to classic yarn, which is outdated, the link was updated to the correct installation page in the [README.md](https://github.com/CLARIAH/vocabulary-recommender/blob/main/README.md).
